import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider";
import { Toaster } from "sonner";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
              {children}
        </Provider>
         <Toaster />
      
      </body>
    </html>
    </ClerkProvider>
    
  );
}


// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { ClerkProvider } from "@clerk/nextjs";
// import Provider from "./provider";
// import { Toaster } from "sonner";

// // Import header & footer components
// import Header from "./_components/Header";
// import Footer from "./_components/Footer";

// // Font setup
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// // Page metadata
// export const metadata = {
//   title: "AI Learn | Online Learning Platform",
//   description: "Explore AI-powered courses and boost your skills.",
// };

// // Root layout
// export default function RootLayout({ children }) {
//   return (
//     <ClerkProvider>
//       <html lang="en">
//         <body
//           className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 text-gray-900`}
//         >
//           <Provider>
//             <Header />
//             <main className="min-h-screen">{children}</main>
//             <Footer />
//           </Provider>
//           <Toaster />
//         </body>
//       </html>
//     </ClerkProvider>
//   );
// }
